DAMP_OF_WIKIDATA_PATH = 'E:\\data_diplom\\wikidata_ru_en_20230703.tar\\wikidata_extracted'
DAMP_OF_WIKIPEDIA_PATH = 'D:\\asd\\ruwiki-20220701-pages-meta-current.xml.bz2'
RUWORDNET_PATH= 'D:\\lbase_data\\ruwordnet.db'
GOLD_DATA = "D:\\lbase_data\\wiki_merge_predict_test_29_11_22.csv"
GOLD_WIKIDATA_DATASET = "D:\\lbase_data\\new_dataset.csv"
ALL_STRAIGHT_GRAPH = "D:\\lbase_data\\all_straight_graph.pickle"
ALL_INVERSE_GRAPH = "D:\\lbase_data\\all_inverse_graph.pickle"
ALL_NEED_ARTICLE = "D:\\lbase_data\\all_need_article.pickle"
PATH_TO_TMP_FILE = "E:\\data_diplom\\"
PATH_TO_WN_XML='D:\\asd\\rwn-2021-05-02/senses.N.xml'